# Generated by Django 5.2.11 on 2026-02-05 17:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'department',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='idx_department_name')],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'job',
                'ordering': ['title'],
                'indexes': [models.Index(fields=['title'], name='idx_job_title')],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('full_name_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('hire_date', models.DateField(default=django.utils.timezone.now)),
                ('nid', models.CharField(blank=True, db_index=True, max_length=14, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{14}$', 'National ID must be exactly 14 digits')], verbose_name='National ID')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employee.department')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
                ('job_title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employee.job')),
            ],
            options={
                'db_table': 'employee',
                'ordering': ['full_name_en'],
                'indexes': [models.Index(fields=['user'], name='idx_emp_user'), models.Index(fields=['nid'], name='idx_emp_nid'), models.Index(fields=['hire_date'], name='idx_emp_hire_date'), models.Index(fields=['full_name_en'], name='idx_emp_name_en'), models.Index(fields=['full_name_ar'], name='idx_emp_name_ar'), models.Index(fields=['department', 'job_title'], name='idx_emp_dept_job')],
            },
        ),
    ]
