# Generated by Django 5.2.11 on 2026-02-05 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_seed_departments'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='department',
            table=None,
        ),
        migrations.AlterModelTable(
            name='employee',
            table=None,
        ),
        migrations.AlterModelTable(
            name='job',
            table=None,
        ),
    ]
