# Generated by Django 5.2.11 on 2026-02-06 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_department_table_alter_employee_table_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OUTransferLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_username', models.CharField(db_index=True, help_text='sAMAccountName of the transferred user', max_length=255, verbose_name='Username')),
                ('employee_display_name', models.CharField(blank=True, help_text='Display name at time of transfer', max_length=255, null=True, verbose_name='Display Name')),
                ('old_ou', models.CharField(help_text='Source Organizational Unit', max_length=255, verbose_name='From OU')),
                ('new_ou', models.CharField(help_text='Destination Organizational Unit', max_length=255, verbose_name='To OU')),
                ('old_dn', models.TextField(help_text='Full Distinguished Name before transfer', verbose_name='Old DN')),
                ('new_dn', models.TextField(blank=True, help_text='Full Distinguished Name after transfer', null=True, verbose_name='New DN')),
                ('database_updated', models.BooleanField(default=False, help_text='Whether database department was updated', verbose_name='DB Updated')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial Success')], db_index=True, default='success', max_length=20, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, help_text='Error details if transfer failed', null=True, verbose_name='Error Message')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the admin who performed the action', null=True, verbose_name='IP Address')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Timestamp')),
                ('notes', models.TextField(blank=True, help_text='Additional notes or comments', null=True, verbose_name='Notes')),
                ('employee', models.ForeignKey(blank=True, help_text='Employee record (if exists in database)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ou_transfer_logs', to='employee.employee', verbose_name='Employee')),
                ('new_department', models.ForeignKey(blank=True, help_text='New department in database', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_to', to='employee.department', verbose_name='New Department')),
                ('old_department', models.ForeignKey(blank=True, help_text='Previous department in database', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_from', to='employee.department', verbose_name='Old Department')),
                ('performed_by', models.ForeignKey(help_text='Admin user who performed the transfer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ou_transfers_performed', to=settings.AUTH_USER_MODEL, verbose_name='Performed By')),
            ],
            options={
                'verbose_name': 'OU Transfer Log',
                'verbose_name_plural': 'OU Transfer Logs',
                'ordering': ['-timestamp'],
                'permissions': [('view_transfer_audit', 'Can view transfer audit logs'), ('export_transfer_audit', 'Can export transfer audit logs')],
                'indexes': [models.Index(fields=['-timestamp'], name='idx_transfer_timestamp'), models.Index(fields=['employee_username'], name='idx_transfer_username'), models.Index(fields=['status'], name='idx_transfer_status'), models.Index(fields=['performed_by', '-timestamp'], name='idx_transfer_user_time')],
            },
        ),
    ]
